version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sepe_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sepe_natural
      POSTGRES_USER: sepe_admin
      POSTGRES_PASSWORD: sepe_2026_secret
    volumes:
      - sepe_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sepe_admin -d sepe_natural" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sepe_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - sepe_redis_data:/data

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    container_name: sepe_api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://sepe_admin:sepe_2026_secret@postgres:5432/sepe_natural?schema=public
      - NETSIS_BRIDGE_URL=http://netsis-bridge:5295
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    container_name: sepe_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1
    depends_on:
      - api

  netsis-bridge:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    container_name: sepe_netsis_bridge
    restart: unless-stopped
    ports:
      - "5295:5295"
    volumes:
      - ../apps/integration/src/SepeNatural.NetsisBridge:/app
    working_dir: /app
    command: dotnet watch run --urls http://0.0.0.0:5295

volumes:
  sepe_pgdata:
  sepe_redis_data:
