version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sepe_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sepe_natural
      POSTGRES_USER: sepe_admin
      POSTGRES_PASSWORD: sepe_2026_secret
    volumes:
      - sepe_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sepe_admin -d sepe_natural" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sepe_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - sepe_redis_data:/data

volumes:
  sepe_pgdata:
  sepe_redis_data:
